//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSXWallet.Plugin.Nfse.ProxyServiceNFse {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nfse.abrasf.org.br", ConfigurationName="ProxyServiceNFse.NfseWSServiceSoap")]
    public interface NfseWSServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (GerarNfseRequest) of message GerarNfseRequest does not match the default value (GerarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/GerarNfse", ReplyAction="*")]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseResponse GerarNfse(MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/GerarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseResponse> GerarNfseAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CancelarNfseRequest) of message CancelarNfseRequest does not match the default value (CancelarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/CancelarNfse", ReplyAction="*")]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseResponse CancelarNfse(MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/CancelarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseResponse> CancelarNfseAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SubstituirNfseRequest) of message SubstituirNfseRequest does not match the default value (SubstituirNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/SubstituirNfse", ReplyAction="*")]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseResponse SubstituirNfse(MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/SubstituirNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseResponse> SubstituirNfseAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (RecepcionarLoteRpsSincronoRequest) of message RecepcionarLoteRpsSincronoRequest does not match the default value (RecepcionarLoteRpsSincrono)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono", ReplyAction="*")]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoResponse RecepcionarLoteRpsSincrono(MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono", ReplyAction="*")]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (RecepcionarLoteRpsRequest) of message RecepcionarLoteRpsRequest does not match the default value (RecepcionarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRps", ReplyAction="*")]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsResponse RecepcionarLoteRps(MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarLoteRpsRequest) of message ConsultarLoteRpsRequest does not match the default value (ConsultarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarLoteRps", ReplyAction="*")]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsResponse ConsultarLoteRps(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarNfseServicoPrestadoRequest) of message ConsultarNfseServicoPrestadoRequest does not match the default value (ConsultarNfseServicoPrestado)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado", ReplyAction="*")]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoResponse ConsultarNfseServicoPrestado(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado", ReplyAction="*")]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarNfseServicoTomadoRequest) of message ConsultarNfseServicoTomadoRequest does not match the default value (ConsultarNfseServicoTomado)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoTomado", ReplyAction="*")]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoResponse ConsultarNfseServicoTomado(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoTomado", ReplyAction="*")]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorFaixaRequest) of message ConsultarNfsePorFaixaRequest does not match the default value (ConsultarNfsePorFaixa)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorFaixa", ReplyAction="*")]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaResponse ConsultarNfsePorFaixa(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorFaixa", ReplyAction="*")]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorRpsRequest) of message ConsultarNfsePorRpsRequest does not match the default value (ConsultarNfsePorRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorRps", ReplyAction="*")]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsResponse ConsultarNfsePorRps(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorRps", ReplyAction="*")]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class GerarNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public GerarNfseRequest() {
        }
        
        public GerarNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class GerarNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public GerarNfseResponse() {
        }
        
        public GerarNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class CancelarNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public CancelarNfseRequest() {
        }
        
        public CancelarNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class CancelarNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public CancelarNfseResponse() {
        }
        
        public CancelarNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubstituirNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class SubstituirNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public SubstituirNfseRequest() {
        }
        
        public SubstituirNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubstituirNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class SubstituirNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public SubstituirNfseResponse() {
        }
        
        public SubstituirNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincronoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsSincronoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsSincronoRequest() {
        }
        
        public RecepcionarLoteRpsSincronoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincronoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsSincronoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsSincronoResponse() {
        }
        
        public RecepcionarLoteRpsSincronoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsRequest() {
        }
        
        public RecepcionarLoteRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsResponse() {
        }
        
        public RecepcionarLoteRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarLoteRpsRequest() {
        }
        
        public ConsultarLoteRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarLoteRpsResponse() {
        }
        
        public ConsultarLoteRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoPrestadoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoPrestadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoPrestadoRequest() {
        }
        
        public ConsultarNfseServicoPrestadoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoPrestadoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoPrestadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoPrestadoResponse() {
        }
        
        public ConsultarNfseServicoPrestadoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoTomadoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoTomadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoTomadoRequest() {
        }
        
        public ConsultarNfseServicoTomadoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoTomadoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoTomadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoTomadoResponse() {
        }
        
        public ConsultarNfseServicoTomadoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorFaixaRequest() {
        }
        
        public ConsultarNfsePorFaixaRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorFaixaResponse() {
        }
        
        public ConsultarNfsePorFaixaResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorRpsRequest() {
        }
        
        public ConsultarNfsePorRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorRpsResponse() {
        }
        
        public ConsultarNfsePorRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NfseWSServiceSoapChannel : MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NfseWSServiceSoapClient : System.ServiceModel.ClientBase<MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap>, MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap {
        
        public NfseWSServiceSoapClient() {
        }
        
        public NfseWSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NfseWSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfseWSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfseWSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseResponse MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.GerarNfse(MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseRequest request) {
            return base.Channel.GerarNfse(request);
        }
        
        public string GerarNfse(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseResponse retVal = ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).GerarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseResponse> MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.GerarNfseAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseRequest request) {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseResponse> GerarNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.GerarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).GerarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseResponse MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.CancelarNfse(MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseRequest request) {
            return base.Channel.CancelarNfse(request);
        }
        
        public string CancelarNfse(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseResponse retVal = ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).CancelarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseResponse> MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.CancelarNfseAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseRequest request) {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseResponse> CancelarNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.CancelarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).CancelarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseResponse MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.SubstituirNfse(MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseRequest request) {
            return base.Channel.SubstituirNfse(request);
        }
        
        public string SubstituirNfse(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseResponse retVal = ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).SubstituirNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseResponse> MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.SubstituirNfseAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseRequest request) {
            return base.Channel.SubstituirNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseResponse> SubstituirNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.SubstituirNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).SubstituirNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoResponse MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.RecepcionarLoteRpsSincrono(MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoRequest request) {
            return base.Channel.RecepcionarLoteRpsSincrono(request);
        }
        
        public string RecepcionarLoteRpsSincrono(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoResponse retVal = ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).RecepcionarLoteRpsSincrono(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoResponse> MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.RecepcionarLoteRpsSincronoAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoRequest request) {
            return base.Channel.RecepcionarLoteRpsSincronoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsSincronoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).RecepcionarLoteRpsSincronoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsResponse MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.RecepcionarLoteRps(MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsRequest request) {
            return base.Channel.RecepcionarLoteRps(request);
        }
        
        public string RecepcionarLoteRps(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsResponse retVal = ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).RecepcionarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsResponse> MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.RecepcionarLoteRpsAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsRequest request) {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.RecepcionarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).RecepcionarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsResponse MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.ConsultarLoteRps(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsRequest request) {
            return base.Channel.ConsultarLoteRps(request);
        }
        
        public string ConsultarLoteRps(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsResponse retVal = ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).ConsultarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsResponse> MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.ConsultarLoteRpsAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsRequest request) {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).ConsultarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoResponse MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.ConsultarNfseServicoPrestado(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoRequest request) {
            return base.Channel.ConsultarNfseServicoPrestado(request);
        }
        
        public string ConsultarNfseServicoPrestado(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoResponse retVal = ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).ConsultarNfseServicoPrestado(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoResponse> MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.ConsultarNfseServicoPrestadoAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoRequest request) {
            return base.Channel.ConsultarNfseServicoPrestadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoPrestadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).ConsultarNfseServicoPrestadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoResponse MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.ConsultarNfseServicoTomado(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoRequest request) {
            return base.Channel.ConsultarNfseServicoTomado(request);
        }
        
        public string ConsultarNfseServicoTomado(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoResponse retVal = ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).ConsultarNfseServicoTomado(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoResponse> MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.ConsultarNfseServicoTomadoAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoRequest request) {
            return base.Channel.ConsultarNfseServicoTomadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfseServicoTomadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).ConsultarNfseServicoTomadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaResponse MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.ConsultarNfsePorFaixa(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaRequest request) {
            return base.Channel.ConsultarNfsePorFaixa(request);
        }
        
        public string ConsultarNfsePorFaixa(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaResponse retVal = ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).ConsultarNfsePorFaixa(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaResponse> MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.ConsultarNfsePorFaixaAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaRequest request) {
            return base.Channel.ConsultarNfsePorFaixaAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorFaixaRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).ConsultarNfsePorFaixaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsResponse MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.ConsultarNfsePorRps(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsRequest request) {
            return base.Channel.ConsultarNfsePorRps(request);
        }
        
        public string ConsultarNfsePorRps(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsResponse retVal = ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).ConsultarNfsePorRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsResponse> MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap.ConsultarNfsePorRpsAsync(MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsRequest request) {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsRequest inValue = new MSXWallet.Plugin.Nfse.ProxyServiceNFse.ConsultarNfsePorRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((MSXWallet.Plugin.Nfse.ProxyServiceNFse.NfseWSServiceSoap)(this)).ConsultarNfsePorRpsAsync(inValue);
        }
    }
}
